// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: MumBot.proto
#ifndef GRPC_MumBot_2eproto__INCLUDED
#define GRPC_MumBot_2eproto__INCLUDED

#include "MumBot.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace MumBotProto {

class MumBotRPC GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Say(::grpc::ClientContext* context, const ::MumBotProto::TextMessage& request, ::MumBotProto::TextMessageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MumBotProto::TextMessageResponse>> AsyncSay(::grpc::ClientContext* context, const ::MumBotProto::TextMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MumBotProto::TextMessageResponse>>(AsyncSayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::MumBotProto::TextMessage>> SubscribeToTextMessages(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::MumBotProto::TextMessage>>(SubscribeToTextMessagesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::MumBotProto::TextMessage>> AsyncSubscribeToTextMessages(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::MumBotProto::TextMessage>>(AsyncSubscribeToTextMessagesRaw(context, request, cq, tag));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MumBotProto::TextMessageResponse>* AsyncSayRaw(::grpc::ClientContext* context, const ::MumBotProto::TextMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::MumBotProto::TextMessage>* SubscribeToTextMessagesRaw(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::MumBotProto::TextMessage>* AsyncSubscribeToTextMessagesRaw(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Say(::grpc::ClientContext* context, const ::MumBotProto::TextMessage& request, ::MumBotProto::TextMessageResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MumBotProto::TextMessageResponse>> AsyncSay(::grpc::ClientContext* context, const ::MumBotProto::TextMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MumBotProto::TextMessageResponse>>(AsyncSayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::MumBotProto::TextMessage>> SubscribeToTextMessages(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::MumBotProto::TextMessage>>(SubscribeToTextMessagesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::MumBotProto::TextMessage>> AsyncSubscribeToTextMessages(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::MumBotProto::TextMessage>>(AsyncSubscribeToTextMessagesRaw(context, request, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::MumBotProto::TextMessageResponse>* AsyncSayRaw(::grpc::ClientContext* context, const ::MumBotProto::TextMessage& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientReader< ::MumBotProto::TextMessage>* SubscribeToTextMessagesRaw(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::MumBotProto::TextMessage>* AsyncSubscribeToTextMessagesRaw(::grpc::ClientContext* context, const ::MumBotProto::TextMessageRequest& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Say_;
    const ::grpc::RpcMethod rpcmethod_SubscribeToTextMessages_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Say(::grpc::ServerContext* context, const ::MumBotProto::TextMessage* request, ::MumBotProto::TextMessageResponse* response);
    virtual ::grpc::Status SubscribeToTextMessages(::grpc::ServerContext* context, const ::MumBotProto::TextMessageRequest* request, ::grpc::ServerWriter< ::MumBotProto::TextMessage>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Say : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Say() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Say() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Say(::grpc::ServerContext* context, const ::MumBotProto::TextMessage* request, ::MumBotProto::TextMessageResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSay(::grpc::ServerContext* context, ::MumBotProto::TextMessage* request, ::grpc::ServerAsyncResponseWriter< ::MumBotProto::TextMessageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubscribeToTextMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SubscribeToTextMessages() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SubscribeToTextMessages() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeToTextMessages(::grpc::ServerContext* context, const ::MumBotProto::TextMessageRequest* request, ::grpc::ServerWriter< ::MumBotProto::TextMessage>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeToTextMessages(::grpc::ServerContext* context, ::MumBotProto::TextMessageRequest* request, ::grpc::ServerAsyncWriter< ::MumBotProto::TextMessage>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Say<WithAsyncMethod_SubscribeToTextMessages<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Say : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Say() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Say() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Say(::grpc::ServerContext* context, const ::MumBotProto::TextMessage* request, ::MumBotProto::TextMessageResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubscribeToTextMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SubscribeToTextMessages() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SubscribeToTextMessages() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeToTextMessages(::grpc::ServerContext* context, const ::MumBotProto::TextMessageRequest* request, ::grpc::ServerWriter< ::MumBotProto::TextMessage>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace MumBotProto


#endif  // GRPC_MumBot_2eproto__INCLUDED
