// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: mumbot.proto

#include "mumbot.pb.h"
#include "mumbot.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace libmumbot {

static const char* MumBotRPC_method_names[] = {
  "/libmumbot.MumBotRPC/Say",
  "/libmumbot.MumBotRPC/SubscribeToTextMessages",
};

std::unique_ptr< MumBotRPC::Stub> MumBotRPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< MumBotRPC::Stub> stub(new MumBotRPC::Stub(channel));
  return stub;
}

MumBotRPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Say_(MumBotRPC_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubscribeToTextMessages_(MumBotRPC_method_names[1], ::grpc::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status MumBotRPC::Stub::Say(::grpc::ClientContext* context, const ::libmumbot::TextMessage& request, ::libmumbot::TextMessageResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Say_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::libmumbot::TextMessageResponse>* MumBotRPC::Stub::AsyncSayRaw(::grpc::ClientContext* context, const ::libmumbot::TextMessage& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::libmumbot::TextMessageResponse>(channel_.get(), cq, rpcmethod_Say_, context, request);
}

::grpc::ClientReader< ::libmumbot::TextMessage>* MumBotRPC::Stub::SubscribeToTextMessagesRaw(::grpc::ClientContext* context, const ::libmumbot::TextMessageRequest& request) {
  return new ::grpc::ClientReader< ::libmumbot::TextMessage>(channel_.get(), rpcmethod_SubscribeToTextMessages_, context, request);
}

::grpc::ClientAsyncReader< ::libmumbot::TextMessage>* MumBotRPC::Stub::AsyncSubscribeToTextMessagesRaw(::grpc::ClientContext* context, const ::libmumbot::TextMessageRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReader< ::libmumbot::TextMessage>(channel_.get(), cq, rpcmethod_SubscribeToTextMessages_, context, request, tag);
}

MumBotRPC::Service::Service() {
  (void)MumBotRPC_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      MumBotRPC_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< MumBotRPC::Service, ::libmumbot::TextMessage, ::libmumbot::TextMessageResponse>(
          std::mem_fn(&MumBotRPC::Service::Say), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      MumBotRPC_method_names[1],
      ::grpc::RpcMethod::SERVER_STREAMING,
      new ::grpc::ServerStreamingHandler< MumBotRPC::Service, ::libmumbot::TextMessageRequest, ::libmumbot::TextMessage>(
          std::mem_fn(&MumBotRPC::Service::SubscribeToTextMessages), this)));
}

MumBotRPC::Service::~Service() {
}

::grpc::Status MumBotRPC::Service::Say(::grpc::ServerContext* context, const ::libmumbot::TextMessage* request, ::libmumbot::TextMessageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MumBotRPC::Service::SubscribeToTextMessages(::grpc::ServerContext* context, const ::libmumbot::TextMessageRequest* request, ::grpc::ServerWriter< ::libmumbot::TextMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace libmumbot

